# Generated by Django 4.2.3 on 2024-01-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0002_alter_delivery_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="time",
            field=models.DateField(),
        ),
    ]
