# Generated by Django 5.0.1 on 2024-01-30 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0004_alter_delivery_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="time",
            field=models.DateTimeField(
                choices=[
                    (datetime.datetime(2024, 1, 31, 15, 24, 4, 836404), "1 day later"),
                    (datetime.datetime(2024, 2, 2, 15, 24, 4, 836404), "3 days later"),
                    (datetime.datetime(2024, 2, 6, 15, 24, 4, 836404), "7 days later"),
                ]
            ),
        ),
    ]
