# Generated by Django 5.0.1 on 2024-01-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0006_alter_delivery_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="time",
            field=models.CharField(
                choices=[
                    ("one day", "one day later"),
                    ("three days", "three days later"),
                    ("seven days", "seven days later"),
                ],
                max_length=50,
            ),
        ),
    ]
